parameters:
  - name: deployBasePath
    type: string
    default: ''

  - name: azureSubscription
    type: string
    default: 'UI Fabric (bac044cf-49e1-4843-8dda-1ce9662606c8)'

  # Skip the component governance detection step (injected by a pipeline decorator from an
  # internal extension) by default because we run it separately. Since all our pipelines
  # in each branch install the same packages, only one pipeline (currently the daily release)
  # needs to run detection.
  - name: skipComponentGovernanceDetection
    type: boolean
    default: true

variables:
  deployBasePath: ${{ coalesce(parameters.deployBasePath, 'pr-deploy-site/$(Build.SourceBranch)') }}

  deployHost: 'fabricweb.z5.web.core.windows.net'

  azureSubscription: ${{ parameters.azureSubscription }}

  ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    isPR: true
    targetBranch: 'origin/$(System.PullRequest.TargetBranch)'
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    isPR: false

  skipComponentGovernanceDetection: ${{ parameters.skipComponentGovernanceDetection }}
