variables:
  deployBasePath: "pr-deploy-site/${{ variables['Build.SourceBranch'] }}"

  deployHost: 'fabricweb.z5.web.core.windows.net'

  azureSubscription: 'UI Fabric (bac044cf-49e1-4843-8dda-1ce9662606c8)'

  ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    isPR: true
    targetBranch: 'origin/$(System.PullRequest.TargetBranch)'
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    isPR: false

  backfillProvider: 'azure-blob'
  backfillOptions: '{"connectionString":"$(BACKFILL_CONNECTION_STRING)", "container":"$(BACKFILL_CONTAINER)"}'
