approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Blocked
reset_on_push: false
reject_value: -1
reviewers:
  members:
  - ericthompson
  - Jahnp
  - battletoilet
  - wdo3650
  - mikewheaton
  - dzearing
  - cliffkoh
  - aditima
  - yiminwu
  - antonlabunets
  - cschlechty
  - atneik
  name: pullapprove
  required: 1
