pr: none
trigger: none

variables:
  - group: 'Github and NPM secrets'

pool:
  vmImage: 'Ubuntu 16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      git config user.name "UI Fabric Build"
      git config user.email "fabrictactical@service.microsoft.com"
      git remote set-url origin https://$(githubUser):$(githubPAT)@github.com/OfficeDev/office-ui-fabric-react.git
    displayName: Authenticate git for pushes

  - script: |
      node common/scripts/install-run-rush.js install --bypass-policy
    displayName: rush install

  - script: |
      npm run generate-version-files
    displayName: npm run generate-version-files

  - script: |
      node common/scripts/install-run-rush.js build --production --verbose
    displayName: rush build (Create production build)

  - script: |
      echo Making $(Build.ArtifactStagingDirectory)/api &&
      mkdir -p $(Build.ArtifactStagingDirectory)/api &&
      cp packages/*/dist/*.api.json $(Build.ArtifactStagingDirectory)/api
    displayName: Copy api.json files to artifact staging directory

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)/api
      artifactName: 'api-json'
      publishLocation: 'Container'
    displayName: 'Publish Artifact: api.json'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: apps/fabric-website/dist
      artifactName: 'fabric-website'
      publishLocation: 'Container'
    displayName: 'Publish Artifact: Fabric Website'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: apps/fabric-website/index.html
      artifactName: 'fabric-website-index'
      publishLocation: 'Container'
    displayName: 'Publish Artifact: Fabric Website index.html'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: packages/office-ui-fabric-react/dist
      artifactName: 'fabric'
      publishLocation: 'Container'
    displayName: 'Publish Artifact: Fabric'

  - script: |
      node ./common/scripts/install-run-rush.js publish -a -p -b master -n $(npmToken) --add-commit-details --set-access-level public
    displayName: 'Publish Change Requests and Bump Versions'

  - script: |
      node scripts/updateReleaseNotes.js --token=$(githubPAT) --apply --debug
    displayName: 'Update github release notes'

  - script: |
      oufrVersion=$(node -p -e "require('./packages/office-ui-fabric-react/package.json').version") &&
      echo "OUFR Version: $oufrVersion" &&
      echo $oufrVersion > oufr-version.txt &&
      echo "##vso[task.setvariable variable=oufrVersion;]$oufrVersion"
    displayName: 'Set OUFR Version Task Variable'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: ./oufr-version.txt
      artifactName: 'oufr-version'
      publishLocation: 'Container'
    displayName: 'Publish Artifact: oufr-version.txt'

  - script: |
      npm run create-public-flight-config -- --baseCDNUrl https://fabricweb.azureedge.net/fabric-website/$(Build.BuildNumber)/
    workingDirectory: apps/fabric-website
    displayName: 'Generate Fabric Website Flight Manifest Files'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: apps/fabric-website/flights
      artifactName: 'fabric-website-manifests'
      publishLocation: 'Container'
    displayName: 'Publish Artifact: Website manifests'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: apps/fabric-website-resources/dist
      artifactName: 'fabric-website-resources'
      publishLocation: 'Container'
    displayName: 'Publish Artifact: Fabric Website Resources'
