pr: none
trigger: none

# Customize build number to include major version
# Example: v7_20190626.1
name: 'v7_$(Date:yyyyMMdd)$(Rev:.r)'

variables:
  - group: 'Github and NPM secrets'

pool:
  vmImage: 'Ubuntu 16.04'

schedules:
  # minute 0, hour 12 in UTC (5am in UTC+7), any day of month, any month, days 1-5 of week (M-F)
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?tabs=yaml&view=azure-devops#supported-cron-syntax
  - cron: '7 0 * * 1-5'
    displayName: 'Test fake release'
    branches:
      include:
        - elcraig/build-debugging

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      git config user.name "UI Fabric Build"
      git config user.email "fabrictactical@service.microsoft.com"
      git remote set-url origin https://$(githubUser):$(githubPAT)@github.com/OfficeDev/office-ui-fabric-react.git
    displayName: Authenticate git for pushes

  - script: |
      node common/scripts/install-run-rush.js install --bypass-policy
    displayName: rush install

  - script: |
      npm run generate-version-files
    displayName: npm run generate-version-files

  # - script: |
  #     node common/scripts/install-run-rush.js build --production --verbose
  #   displayName: rush build (Create production build)

  - script: |
      node ./common/scripts/install-run-rush.js publish -a --add-commit-details --set-access-level public
      head -n 100 ./packages/office-ui-fabric-react/CHANGELOG.json
    displayName: 'Publish Change Requests and Bump Versions'

  - script: |
      node scripts/updateReleaseNotes.js --token=$(githubPAT) --debug
    displayName: 'Update github release notes'
