pr: none
trigger: none

# Customize build number to include major version
# Example: fluentui_20190626.1
name: 'fluentui_$(Date:yyyyMMdd)$(Rev:.r)'

variables:
  - group: 'Github and NPM secrets'

pool: 'Self Host Ubuntu'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      git config user.name "UI Fabric Build"
      git config user.email "fabrictactical@service.microsoft.com"
      git remote set-url origin https://$(githubUser):$(githubPAT)@github.com/OfficeDev/office-ui-fabric-react.git
    displayName: Authenticate git for pushes

  - script: |
      yarn
    displayName: yarn

  - script: |
      PRODUCTION=true yarn build
    displayName: yarn build

  - script: |
      PRODUCTION=true yarn build:fluentuidocs
    displayName: yarn build:fluentuidocs

  - task: AzureUpload@1
    displayName: Upload docs site
    inputs:
      SourcePath: 'packages/fluentui/docs/dist'
      azureSubscription: 'UI Fabric (bac044cf-49e1-4843-8dda-1ce9662606c8)'
      storage: fluentsite
      ContainerName: '$web'
      BlobPrefix: ''

  - script: |
      yarn test
    displayName: yarn test

  - script: |
      yarn lint
    displayName: yarn lint
  # - script: |
  #     yarn fluentui:release:$(bumpType)
